#!/usr/bin/python
# Copyright 2010 Google Inc.
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0

# Google's Python Class
# http://code.google.com/edu/languages/google-python-class/

import os
import re
import sys
import urllib

"""Logpuzzle exercise
Given an apache logfile, find the puzzle urls and download the images.

Here's what a puzzle url looks like:
10.254.254.28 - - [06/Aug/2007:00:13:48 -0700] "GET /~foo/puzzle-bar-aaab.jpg HTTP/1.0" 302 528 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
"""


def read_urls(filename):
  """Returns a list of the puzzle urls from the given log file,
  extracting the hostname from the filename itself.
  Screens out duplicate urls and returns the urls sorted into
  increasing order."""
  # +++your code here+++
  url=''
  l=[]
  p='GET\s*([/a-zA-Z0-9-]+)\S'
  import re
  #for file in filename:
  try:
    f=open(filename, 'r')
    s=f.read()
  except:
    pass
  m=re.findall(p,s)
  if m:
      for match in m:
        #print match
        if 'puzzle' in match:
          url='http://www.' + filename + match
          if url not in l:
            print "im here"
          #print type(url) 
            l.append(url) 
        else:
          print "puzzle not present in file"
  else:
      print "no match"   
  #print type(l)
  print '*' * 80
  r=sorted(l)
  print type(l)
  print r 
  try:
    f.close()
  except:
    pass
  return r     
  

def download_images(img_urls, dest_dir):
  """Given the urls already in the correct order, downloads
  each image into the given directory.
  Gives the images local filenames img0, img1, and so on.
  Creates an index.html in the directory
  with an img tag to show each local image file.
  Creates the directory if necessary.
  """
  print '&' * 80
  #print img_urls
  #l=read_urls(img_urls)
  if not os.path.isdir(dest_dir):
    os.makedirs(dest_dir)
  i=0
  
  for url in img_urls:
    print url
    n='%s' % i
    path = dest_dir + '/' + 'img' + n
    print path
    print "Retreiving image...."
    urllib.urlretrieve(url, path)
    i+=1

  # +++your code here+++
  

def main():
  args = sys.argv[1:]

  if not args:
    print 'usage: [--todir dir] logfile '
    sys.exit(1)

  todir = ''
  if args[0] == '--todir':
    todir = args[1]
    del args[0:2]

  img_urls = read_urls(args[0])

  if todir:
    download_images(img_urls, todir)
  else:
    print '\n'.join(img_urls)

if __name__ == '__main__':
  main()
